name: hand_cricket_game
description: "A Hand Cricket Game built with Flutter and Rive animations."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  rive: ^0.12.4
  just_audio: ^0.9.34
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/overlays/
    - assets/riv/
    - assets/music/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/hand_cricket_logo.png"
